# conda env create --file environment.yml
name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge (no es oficial, pero es muy bueno y tiene una gran comunidad)
  - defaults
dependencies:
  {% if cookiecutter.project_packages == "all" -%}
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pandas
  - requests
  - seaborn
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - statsmodels
  {% endif -%}
  - pip
  {% if cookiecutter.project_packages == "all" -%}
  - pyprojroot
  {% endif -%}
  - python={{ cookiecutter.python_version }}
  - pip:
    {% if cookiecutter.project_packages == "all" -%}
    - pyhere
    {% endif -%}

